# Generated by Django 3.1.5 on 2021-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserie',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='portada/', verbose_name='Imagen de portada'),
        ),
    ]
