# Generated by Django 3.1.5 on 2021-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20211212_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpuntuacion',
            name='puntuacion',
            field=models.CharField(choices=[('0', 'Ninguno'), ('1', 'Muy Baja'), ('2', 'Baja'), ('3', 'Media'), ('4', 'Alta'), ('5', 'Muy Alta')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.CharField(choices=[('0', 'Ninguno'), ('1', 'Muy Baja'), ('2', 'Baja'), ('3', 'Media'), ('4', 'Alta'), ('5', 'Muy Alta')], default='0', max_length=1),
        ),
    ]
