# Generated by Django 4.2.6 on 2023-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('descripcion',), 'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterField(
            model_name='historicalserie',
            name='promedio_puntuaciones_imdb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='promedio_puntuaciones_imdb'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.ManyToManyField(blank=True, to='principal.genero'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='promedio_puntuaciones_imdb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='promedio_puntuaciones_imdb'),
        ),
    ]
