# Generated by Django 4.0 on 2022-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_categoria_historicalserie_promedio_puntuaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserie',
            name='promedio_puntuaciones',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='serie',
            name='promedio_puntuaciones',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
