# Generated by Django 4.0 on 2022-01-26 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_historicalserie_promedio_puntuaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserie',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='portada/%Y/%m/%d/', verbose_name='Imagen de portada'),
        ),
    ]
