# Generated by Django 4.2.5 on 2023-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_genero_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcategoria',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoría', 'verbose_name_plural': 'historical Categorías'},
        ),
        migrations.AlterModelOptions(
            name='historicalepisodio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Episodio', 'verbose_name_plural': 'historical Episodios'},
        ),
        migrations.AlterModelOptions(
            name='historicalgenero',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Género', 'verbose_name_plural': 'historical Géneros'},
        ),
        migrations.AlterModelOptions(
            name='historicalpuntuacion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Puntuación', 'verbose_name_plural': 'historical Puntuaciones'},
        ),
        migrations.AlterModelOptions(
            name='historicalserie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Serie', 'verbose_name_plural': 'historical Series'},
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalepisodio',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgenero',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpuntuacion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalserie',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
