# Generated by Django 4.2.5 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_historicalcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpuntuacion',
            name='puntuacion',
            field=models.CharField(choices=[('0', 'Ninguno'), ('1', 'Pesima'), ('2', 'Muy Baja'), ('3', 'Baja'), ('4', 'Bajo la Media'), ('5', 'Media'), ('6', 'Encima de la Media'), ('7', 'Alta'), ('8', 'Muy Alta'), ('9', 'Exelente'), ('10', 'Excepcional')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalserie',
            name='promedio_puntuaciones',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.CharField(choices=[('0', 'Ninguno'), ('1', 'Pesima'), ('2', 'Muy Baja'), ('3', 'Baja'), ('4', 'Bajo la Media'), ('5', 'Media'), ('6', 'Encima de la Media'), ('7', 'Alta'), ('8', 'Muy Alta'), ('9', 'Exelente'), ('10', 'Excepcional')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='serie',
            name='promedio_puntuaciones',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
