# Generated by Django 4.2.5 on 2023-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_historicalpuntuacion_puntuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserie',
            name='cantidad_episodios',
            field=models.IntegerField(default=0, verbose_name='Cantidad de episodios'),
        ),
        migrations.AddField(
            model_name='historicalserie',
            name='link_imdb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalserie',
            name='promedio_puntuaciones_imdb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serie',
            name='cantidad_episodios',
            field=models.IntegerField(default=0, verbose_name='Cantidad de episodios'),
        ),
        migrations.AddField(
            model_name='serie',
            name='link_imdb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='promedio_puntuaciones_imdb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
