# Generated by Django 4.2.5 on 2023-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_historicalserie_cantidad_episodios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserie',
            name='color_carta',
            field=models.CharField(choices=[('grey', 'Ninguna'), ('green', 'Corta'), ('yellow', 'Media'), ('orange', 'Ampliada'), ('pink', 'Larga'), ('blue', 'Extensa'), ('purple', 'Epica'), ('black', 'Legendaria')], default='grey', max_length=8),
        ),
        migrations.AddField(
            model_name='serie',
            name='color_carta',
            field=models.CharField(choices=[('grey', 'Ninguna'), ('green', 'Corta'), ('yellow', 'Media'), ('orange', 'Ampliada'), ('pink', 'Larga'), ('blue', 'Extensa'), ('purple', 'Epica'), ('black', 'Legendaria')], default='grey', max_length=8),
        ),
    ]
