# Generated by Django 4.2.5 on 2023-09-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_historicalserie_color_carta_serie_color_carta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserie',
            name='color_carta',
            field=models.CharField(choices=[('grey', 'Ninguna'), ('green', 'Corta'), ('yellow', 'Media'), ('orange', 'Ampliada'), ('pink', 'Larga'), ('blue', 'Extensa'), ('purple', 'Epica'), ('black', 'Legendaria')], default='grey', max_length=8, verbose_name='Duracion de la serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='color_carta',
            field=models.CharField(choices=[('grey', 'Ninguna'), ('green', 'Corta'), ('yellow', 'Media'), ('orange', 'Ampliada'), ('pink', 'Larga'), ('blue', 'Extensa'), ('purple', 'Epica'), ('black', 'Legendaria')], default='grey', max_length=8, verbose_name='Duracion de la serie'),
        ),
    ]
