# Generated by Django 4.2.5 on 2023-10-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_color_historicalcolor_historicalserie_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.RemoveField(
            model_name='historicalserie',
            name='color_carta',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='color_carta',
        ),
        migrations.AlterField(
            model_name='historicalserie',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.categoria'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.categoria'),
        ),
    ]
