# Generated by Django 4.2.5 on 2023-10-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_color_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='historicalgenero',
            name='cantidad',
        ),
    ]
