# Generated by Django 4.2.6 on 2023-10-05 22:55

from django.db import migrations, models
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndBar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('image', models.ImageField(max_length=255, upload_to='endbar/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('localStorageKey', models.CharField(db_index=True, max_length=80, unique=True)),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('ORDENAR', 'Ordenar'), ('TRANSMISION', 'Transmision'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha'), ('PUNTUACION', 'Puntuacion')], default='LISTAR', max_length=16)),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtros',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalEndBar',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(blank=True, editable=False)),
                ('nombre', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('image', models.TextField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Tecnologia',
                'verbose_name_plural': 'historical Tecnologias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFiltro',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(blank=True, editable=False)),
                ('nombre', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('localStorageKey', models.CharField(db_index=True, max_length=80)),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('ORDENAR', 'Ordenar'), ('TRANSMISION', 'Transmision'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha'), ('PUNTUACION', 'Puntuacion')], default='LISTAR', max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Filtro',
                'verbose_name_plural': 'historical Filtros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMenu',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(blank=True, editable=False)),
                ('nombre', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('image', models.TextField(max_length=255)),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información'), ('USER', 'Administracion')], default='LISTAR', max_length=16)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Menu',
                'verbose_name_plural': 'historical Menuses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True, verbose_name='modifieddate')),
                ('deleted_date', models.DateField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('image', models.ImageField(max_length=255, upload_to='icons/')),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información'), ('USER', 'Administracion')], default='LISTAR', max_length=16)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menuses',
            },
        ),
    ]
