# Generated by Django 4.2.5 on 2023-09-18 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('localStorageKey', models.CharField(db_index=True, max_length=80, unique=True)),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha')], default='LISTAR', max_length=16)),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtros',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('image', models.ImageField(max_length=255, upload_to='icons/', verbose_name='Icono')),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información')], default='LISTAR', max_length=16)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menuses',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMenu',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('image', models.TextField(max_length=255, verbose_name='Icono')),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información')], default='LISTAR', max_length=16)),
                ('content', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Menu',
                'verbose_name_plural': 'historical Menuses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFiltro',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(db_index=True, max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=80)),
                ('localStorageKey', models.CharField(db_index=True, max_length=80)),
                ('clasificacion', models.CharField(choices=[('LISTAR', 'Listar'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha')], default='LISTAR', max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Filtro',
                'verbose_name_plural': 'historical Filtros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
