# Generated by Django 4.2.5 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='clasificacion',
            field=models.CharField(choices=[('LISTAR', 'Listar'), ('ORDENAR', 'Ordenar'), ('TRANSMISION', 'Transmision'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha'), ('PUNTUACION', 'Puntuacion')], default='LISTAR', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalfiltro',
            name='clasificacion',
            field=models.CharField(choices=[('LISTAR', 'Listar'), ('ORDENAR', 'Ordenar'), ('TRANSMISION', 'Transmision'), ('AUTOCOMPLETAR', 'Autocompletar'), ('FECHA', 'Fecha'), ('PUNTUACION', 'Puntuacion')], default='LISTAR', max_length=16),
        ),
    ]
