# Generated by Django 4.2.6 on 2023-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='image',
            field=models.ImageField(default='none.png', max_length=255, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='historicalfiltro',
            name='image',
            field=models.TextField(default='none.png', max_length=255),
        ),
    ]
