# Generated by Django 4.2.5 on 2023-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_filtro_clasificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('orden',), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menuses'},
        ),
        migrations.AddField(
            model_name='historicalmenu',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
