# Generated by Django 4.2.5 on 2023-09-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_menu_options_historicalmenu_orden_menu_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menuses'},
        ),
    ]
