# Generated by Django 4.2.5 on 2023-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmenu',
            name='clasificacion',
            field=models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información'), ('USER', 'Administracion')], default='LISTAR', max_length=16),
        ),
        migrations.AlterField(
            model_name='menu',
            name='clasificacion',
            field=models.CharField(choices=[('LISTAR', 'Listar'), ('INFO', 'Información'), ('USER', 'Administracion')], default='LISTAR', max_length=16),
        ),
    ]
