# Generated by Django 4.2.5 on 2023-10-03 00:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_historicalmenu_clasificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmenu',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
