# Generated by Django 4.2.5 on 2023-10-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_endbar_historicalendbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endbar',
            options={'ordering': ('orden',), 'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
    ]
